# Generated by Django 2.2.3 on 2019-08-04 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_auto_20190804_1449'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='image',
            field=models.ImageField(default=454, upload_to='./images/'),
            preserve_default=False,
        ),
    ]
